site_name: Open PHD Guiding
site_url: https://openphdguiding.org/static
repo_url: https://github.com/OpenPHDGuiding/phd2
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  logo: assets/phd2_32.png
  favicon: assets/phd2_32.png
  palette:
    scheme: slate
    primary: teal
plugins:
  - search
  - blog:
      archive: false
      categories: false
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
nav:
  - Home: index.md
  - Features: features.md
  - News: blog/index.md
  - Changelog: changelog.md
  - Download: downloads.md
  - Documentation: documentation.md
  - Getting Help: getting-help.md
  - About: about.md
